services:
  dev:
    profiles: ["dev"]
    image: node:20-alpine
    working_dir: /workspace
    command: sh -lc "npm ci && CHOKIDAR_USEPOLLING=true CHOKIDAR_INTERVAL=300 npm run start -- --host 0.0.0.0"
    ports:
      - "4200:4200"
    volumes:
      - .:/workspace
      - node_modules_cache:/workspace/node_modules # cache de dependências
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true

  app:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  node_modules_cache:
